apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: bmi-app
data:
  NODE_ENV:     "production"
  PORT:         "3000"
  # Set to the master node public IP and the frontend NodePort
  FRONTEND_URL: "http://13.127.210.35:30080"
