apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: bmi-app
data:
  NODE_ENV:     "production"
  PORT:         "3000"
  # Set to the master node public IP and the frontend NodePort
  FRONTEND_URL: "http://3.110.161.247:30080"
