apiVersion: v1
kind: Service
metadata:
  name: bmi-backend-svc
  namespace: bmi-app
spec:
  # ClusterIP: only reachable inside the cluster (nginx proxies to it)
  type: ClusterIP
  selector:
    app: bmi-backend
  ports:
    - port:       3000
      targetPort: 3000
      protocol:   TCP
