apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: bmi-app
type: Opaque
# IMPORTANT: Update the password below to match what you set in postgres/secret.yaml
stringData:
  DATABASE_URL: "postgres://bmi_user:0stad2025@bmi-postgres-svc:5432/bmidb"
